version: '3'
services:

    swagger:
        image: swaggerapi/swagger-ui
        container_name: swagger
        restart: always
        environment:
            USER: mtsouk
        ports:
            - 80:8080
        volumes:
            - ./data:/tmp/data
